In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
P = np.zeros((50,50))

In [3]:
P[0,0] = 1/2
P[1,0] = 1/2
P[49,49] = 1/2
P[48,49] = 1/2

In [4]:
for i in range(1,49):
    P[i-1,i] = 1/3
    P[i,i] = 1/3
    P[i+1,i] = 1/3

In [6]:
x = la.solve(P - np.identity(50), np.zeros(50))
x

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=7.9891e-17): result may not be accurate.
  """Entry point for launching an IPython kernel.


array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])

In [45]:
inf_P = np.identity(50)
for i in range(100):
    inf_P = inf_P * P

In [84]:
Ld

array([[0.5       , 0.33333333, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.33333333, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.33333333,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [38]:
p = np.ones(50)/50

In [42]:
a  =  @ p

In [55]:
np.zeros(50).T

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
a = np.array([1,2])
b = a

In [64]:
a @ b

5